#!/bin/bash
echo "========================================================"
for i in kubernetes_lab_{master,node0{1..2}}
do echo  ""
   echo $i
   echo ---------------
   virsh suspend --domain $i 
done

echo " "
echo "========================================================="
echo Done.  All domains suspended.
