#!/bin/bash
echo "========================================================"
for i in kubernetes_lab_{master,node0{1..2}}
do echo  ""
   echo $i
   echo ---------------
   virsh snapshot-revert --domain $i --snapshotname 001_Initial_Setup 
   echo "Snapshot successfully reverted"
done

echo " "
echo "========================================================="
echo Done.  All snapshots reverted.
