#!/bin/bash

echo "========================================================"
for i in kubernetes_lab_{master,node0{1..2}}
do echo  ""
   echo $i 
   echo --------------- 
   virsh snapshot-list --name --domain $i
done

echo " "
echo "========================================================="
echo Done.  All snapshots listed.
