#!/bin/bash
echo "========================================================"
for i in vagrant-kubeadm-k8s-almalinux9_{master,node0{1..2}}
do echo  ""
   echo $i
   echo ---------------
   virsh suspend --domain $i 
done

echo " "
echo "========================================================="
echo Done.  All domains suspended.
