#!/bin/bash

echo "========================================================"
for i in vagrant-kubeadm-k8s-almalinux9_{master,node0{1..2}}
do echo  ""
   echo $i 
   echo --------------- 
   virsh snapshot-list --name --domain $i
done

echo " "
echo "========================================================="
echo Done.  All snapshots listed.
